WORKS!!
MiguelRodriguezSerrano/apiRest-node-mongo-ts pull request #1
Opened 2019-07-10 10:40 UTC by MiguelRodriguezSerrano

Change to ts

2019-07-17 10:54 UTC, raulanatol requested changes

2019-07-17 10:54 UTC, raulanatol commented on build/server.js
>  const express_1 = __importDefault(require("express"));
Cuidado con subir los compilados al repositorio.
Deberías de poner en el .gitignore el directorio build
Y luego como ya lo has subido va a pasar por lo que tendrías que ejecutar
```
git rm -R --cached build
```
Para que borre el build de la cache del git

2019-07-17 10:54 UTC, raulanatol commented on package.json
> -    "@types/compression": "0.0.36",
Los @types intenta ponerlos siempre en devDevpendencies

2019-07-17 10:55 UTC, raulanatol commented
Te he metido un par de comentarios pero el código pinta muy bien 😉 
¡Buen trabajo!

2019-07-20 19:19 UTC, MiguelRodriguezSerrano commented
Vale, tomo nota, sabía que los fallos del @types y el gitignore me los ibas
a decir, por que cuando hice la pull request me di cuenta.

Mucgas gracias.

El mié., 17 jul. 2019 a las 12:55, Raúl Anatol (<notifications@github.com>)
escribió:

> Te he metido un par de comentarios pero el código pinta muy bien 😉
> ¡Buen trabajo!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MiguelRodriguezSerrano/apiRest-node-mongo-ts/pull/1?email_source=notifications&email_token=AMCJFYJ3ZQM7DSYZDYE6GWDP733ALA5CNFSM4H7N7CZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2D2D4I#issuecomment-512205297>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMCJFYJ3OHPIWDLGKXE3YATP733ALANCNFSM4H7N7CZA>
> .
>

2019-11-11 15:33 UTC, closed without merging